### ISSUE TITLE
res=[]は不要？

### ISSUE THREAD

**Issue by shisyax** [kujirahand/book-python-scraping#1]
14行目で宣言しているresがどこにも使われていませんが不要でしょうか。

**Comment by bdgcp** [comment]
mnist-tocsvのres=[]でエラーが出る奴なら、本では上の*cols改行されてておかしいみたいなんで、その上のpixels=rowsとつなげて、pixels=rows*colsにしたら動いたですよ

**Comment by kujirahand** [comment]
p190 res = [] は不要なので削除しました。
